## daftacademy

In [1]:
import pandas as pd
import numpy as np

In [2]:
file = r'C:\Users\Asia\Documents\daft academy\dane.csv'

df = pd.read_csv(file,  sep = ";", low_memory=False)
df.head()

LK-SG Nellie (Feedermax)  \
0    MA-SG-83996625/2585/A1@oxlyo.uk/6145   
1  LK-SG-65041225/2292/X2@kldkrh.hr/99361   
2   LK-SG-56103708/2888/Z1@husvb.cl/93519   
3    LK-SG-34905922/2908/A2@jeck.ar/67001   
4   LK-SG-70365073/2973/B3@uexkc.ne/32974   

                 PA-OM Ghost (New Panamax)  \
0      PA-ES-96031647/2993/B2@tuw.ml/94044   
1  PA-OM-51292344/2432/Y2@cnnlgrt.ml/11242   
2      SA-SA-73465451/1924/B3@rej.ba/38170   
3    PA-ID-94657093/2370/X2@jpllu.ls/93944   
4     PA-OM-34467231/4591/Y2@hoox.ca/18710   

                           GR-BE Blue (ULCV)  \
0  MY-BE-40283751/4079/X1@nxocoezoq.mp/96326   
1     GR-BE-20853894/2657/Y2@rlzkic.dk/19799   
2       SA-GB-27472314/1430/Y2@vwit.ne/62695   
3       GR-BE-26706350/3679/X1@tjpy.ua/92050   
4   GR-BE-66955426/2830/Y2@ssaysqgy.nz/81484   

            ID-VN Charlotte (Small feeder)  \
0   ID-VN-33266337/3165/Y2@uineka.se/69047   
1    BE-BE-29634771/2841/Z1@aerrv.pa/98217   
2  ID-VN-85411865/2549/B2@upthpgw.sb/87360   
3    ID-VN-15537738/3270/Y2@dtpcc.my/64445   
4     VN-IN-06555743/2249/Y1@ltor.ne/40761   

               BE-CA Belafonte (Post-Panamax)  \
0        BE-CA-89905813/3223/C2@ltor.ne/68920   
1        BE-CA-38311826/3576/B3@jbkk.bf/71926   
2      BE-CA-42006271/1499/C1@pvvvtv.my/92789   
3  BE-CA-02105662/4492/Y1@irmqicyeym.cl/91984   
4     TH-CA-75372193/1736/Z1@pzhdqej.mn/13050   

              MT-TH Speranza (New Panamax)  \
0  MT-TH-24923449/3639/C1@gpkapat.ge/53411   
1  DE-TH-62431607/1371/A1@qclajsg.ba/65645   
2    PH-TH-23141480/4337/C2@fukcw.sh/76034   
3    IN-LK-92283518/2950/A2@bqsbs.nz/38914   
4      MT-TH-15078686/3388/A1@mju.co/56044   

                           GR-ES China (ULCV)  \
0  ES-ES-05199984/1845/B2@recfkuwwsb.ml/19278   
1        GR-ES-74799208/4373/A2@srbh.cl/51634   
2        VN-MT-71958819/4118/X2@ofjx.af/42364   
3       PA-ES-28310638/4323/C3@psrun.ca/96238   
4  SA-ES-13902353/2942/A3@hsxpkywomc.na/86488   

                 VN-SA Corsair (New Panamax)  \
0    TH-SA-52347518/3566/A3@gzisqdnt.my/8813   
1      PH-SA-51770171/2249/A2@vmrxb.at/62140   
2  VN-SA-22726083/2238/B3@macsamsyj.mf/46624   
3   VN-SA-69444675/1857/A2@egkobucw.ge/95057   
4    VN-SA-09898403/2190/Y2@euvzdhh.ls/13709   

                     ES-TW Altair (Feedermax)  \
0       ES-GR-37106935/3029/C2@stpsdv.fi/9291   
1   PA-TH-25471644/2492/C3@nxocoezoq.mp/47376   
2         PH-TW-03146399/2033/Z1@xlwx.ls/4574   
3  ES-IN-73522503/3425/B3@ztxvgwpitj.at/66720   
4       MT-TW-83861023/3034/Z1@gsvub.sm/78964   

                 SA-ES Tankadère (Feedermax)  ...  \
0     SA-ES-37956461/3478/B3@bwzwzu.sy/83214  ...   
1       LK-ES-89417715/1422/A2@tlrg.gs/51074  ...   
2        SA-ES-97019635/3894/X1@kij.ml/57386  ...   
3      SA-ES-07195573/2586/A2@hhzfo.ca/97473  ...   
4  SA-ES-94014368/3324/B1@tpjdlrbcp.gq/45012  ...   

                         BE-SA Cithara (ULCV)  \
0      BE-SA-09382878/1696/X1@umaxcu.fi/72069   
1         JP-SA-87795748/3862/C2@pqn.cu/84394   
2  KP-SA-24955317/3070/Z1@wvjgexthvc.my/50507   
3      BE-SA-33286290/4291/X2@gfwqsv.pa/24733   
4      BE-SA-44722253/2862/B3@kzlmita.gm/4285   

                         SG-TH Pushkin (ULCV)  \
0  SG-TH-23167136/4103/C3@zavwszregx.mt/85995   
1        SG-TH-12922418/2289/C3@olzq.hr/44302   
2   SG-TH-72904123/3353/X2@fiogfdbcc.yt/26498   
3  SG-SG-34783081/1762/B1@fkqeselfiw.ps/85738   
4   SG-TH-83697637/4512/A2@urjryzsoj.dk/80954   

                          MT-IN Astrea (ULCV)  \
0     MT-IN-72455571/4036/B2@upthpgw.sb/29389   
1     MT-IN-39542774/3379/B1@rbojxpp.at/18632   
2  MT-IN-04125937/4466/X2@izjuykbkxa.pl/95825   
3       US-IN-31852284/2689/A3@rkzan.ba/93779   
4        MT-IN-21488006/3060/A2@aosl.nz/78592   

               BR-US Grossadler (Feedermax)  \
0    BR-US-41967990/2977/C3@nrmipw.sm/38715   
1  BR-US-07900956/4151/A3@hibktyjq.ar/35773   
2      BR-US-37097564/3180/A2@gwgs.ar/92155   
3  BR-US-28952353/2751/A3@dophbxhl.af/25077   
4       DE-ID

In [18]:
df.shape

(23962, 49)

In [23]:
list(df.columns.values.tolist())

['LK-SG Nellie (Feedermax)',
 'PA-OM Ghost (New Panamax)',
 'GR-BE Blue (ULCV)',
 'ID-VN Charlotte (Small feeder)',
 'BE-CA Belafonte (Post-Panamax)',
 'MT-TH Speranza (New Panamax)',
 'GR-ES China (ULCV)',
 'VN-SA Corsair (New Panamax)',
 'ES-TW Altair (Feedermax)',
 'SA-ES Tankadère (Feedermax)',
 'KP-MY Gotha (ULCV)',
 'ID-BR Cassidy (Feedermax)',
 'GR-TH Nautilus (Post-Panamax)',
 'MT-MY Harekaze (Feeder)',
 'VN-VN Neptune (Panamax)',
 'DE-MY Argonaut (New Panamax)',
 'KP-MY Odessa (Small feeder)',
 'JP-IN Anchises (Panamax)',
 'MY-DE Seagallop (Feeder)',
 'MA-ES Grayfish (Post-Panamax)',
 'CA-KP Reaper (Feeder)',
 'KP-NL Tasha (ULCV)',
 'GR-BE Aeolus (Post-Panamax)',
 'AE-IN Illustria (Small feeder)',
 'BE-GR Argonautica (Feedermax)',
 'PA-ES Pocahontas (Small feeder)',
 'KP-GR Covenant (Feedermax)',
 'MA-PA Ning-Po (Feeder)',
 'MT-MY Demeter (Feedermax)',
 'DE-BE Siren (New Panamax)',
 'GB-IN Argo (ULCV)',
 'OM-GB Vingilot (ULCV)',
 'VN-GR Queequeg (Panamax)',
 'BE-NL Proteus (Sm

In [36]:
df.columns

Index(['LK-SG Nellie (Feedermax)', 'PA-OM Ghost (New Panamax)',
       'GR-BE Blue (ULCV)', 'ID-VN Charlotte (Small feeder)',
       'BE-CA Belafonte (Post-Panamax)', 'MT-TH Speranza (New Panamax)',
       'GR-ES China (ULCV)', 'VN-SA Corsair (New Panamax)',
       'ES-TW Altair (Feedermax)', 'SA-ES Tankadère (Feedermax)',
       'KP-MY Gotha (ULCV)', 'ID-BR Cassidy (Feedermax)',
       'GR-TH Nautilus (Post-Panamax)', 'MT-MY Harekaze (Feeder)',
       'VN-VN Neptune (Panamax)', 'DE-MY Argonaut (New Panamax)',
       'KP-MY Odessa (Small feeder)', 'JP-IN Anchises (Panamax)',
       'MY-DE Seagallop (Feeder)', 'MA-ES Grayfish (Post-Panamax)',
       'CA-KP Reaper (Feeder)', 'KP-NL Tasha (ULCV)',
       'GR-BE Aeolus (Post-Panamax)', 'AE-IN Illustria (Small feeder)',
       'BE-GR Argonautica (Feedermax)', 'PA-ES Pocahontas (Small feeder)',
       'KP-GR Covenant (Feedermax)', 'MA-PA Ning-Po (Feeder)',
       'MT-MY Demeter (Feedermax)', 'DE-BE Siren (New Panamax)',
       'GB-IN Argo (U

In [37]:
df.columns[0]

'LK-SG Nellie (Feedermax)'

In [17]:
df.iloc[[0]]

LK-SG Nellie (Feedermax)            PA-OM Ghost (New Panamax)  \
0  MA-SG-83996625/2585/A1@oxlyo.uk/6145  PA-ES-96031647/2993/B2@tuw.ml/94044   

                           GR-BE Blue (ULCV)  \
0  MY-BE-40283751/4079/X1@nxocoezoq.mp/96326   

           ID-VN Charlotte (Small feeder)  \
0  ID-VN-33266337/3165/Y2@uineka.se/69047   

         BE-CA Belafonte (Post-Panamax)  \
0  BE-CA-89905813/3223/C2@ltor.ne/68920   

              MT-TH Speranza (New Panamax)  \
0  MT-TH-24923449/3639/C1@gpkapat.ge/53411   

                           GR-ES China (ULCV)  \
0  ES-ES-05199984/1845/B2@recfkuwwsb.ml/19278   

               VN-SA Corsair (New Panamax)  \
0  TH-SA-52347518/3566/A3@gzisqdnt.my/8813   

                ES-TW Altair (Feedermax)  \
0  ES-GR-37106935/3029/C2@stpsdv.fi/9291   

              SA-ES Tankadère (Feedermax)  ...  \
0  SA-ES-37956461/3478/B3@bwzwzu.sy/83214  ...   

                     BE-SA Cithara (ULCV)  \
0  BE-SA-09382878/1696/X1@umaxcu.fi/72069   

                         SG-TH Pushkin (ULCV)  \
0  SG-TH-23167136/4103/C3@zavwszregx.mt/85995   

                       MT-IN Astrea (ULCV)  \
0  MT-IN-72455571/4036/B2@upthpgw.sb/29389   

             BR-US Grossadler (Feedermax)  \
0  BR-US-41967990/2977/C3@nrmipw.sm/38715   

                        SA-BR Arabella (ULCV)  \
0  SA-SG-43672447/1694/C3@oiukajaobq.es/85624   

               ES-GR Henrietta (New Panamax)  \
0  ES-GR-34164673/3621/A1@zafttdgib.ge/52829   

            MA-MT Dazzler (New Panamax)         PA-MT Chelsea (Small feeder)  \
0  MA-MT-88483468/1444/A1@vyytj.gs/3473  PA-PA-82963550/3638/C2@tuw.ml/39884   

            SG-US Literature (Post-Panamax)  \
0  SG-US-50886614/1511/B3@gzznqcoyp.pa/7079   

                 AE-IN Unicorn (Panamax)  
0  AE-IN-02236711/1904/A1@qeztc.sm/94381  

[1 rows x 49 columns]

# PYTANIE NR 1 Ile kontenerów finalnie trafi do Japonii (JP)? (liczba kontenerów) – 15 pkt

In [91]:
mask = np.column_stack([ df[s].str.contains("-JP-", na=False) for s in df ])
mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [92]:
mask.sum(where = True)

3779

In [93]:
# (23962, 49)
mask.shape

(23962, 49)

# PYTANIE NR. 2 Jaka klasa statku średnio przewozi najwięcej kontenerów? (sama nazwa klasy statku) – 15 pkt

In [96]:
df_isna = df.isna().copy()
df_isna

LK-SG Nellie (Feedermax)  PA-OM Ghost (New Panamax)  GR-BE Blue (ULCV)  \
0                         False                      False              False   
1                         False                      False              False   
2                         False                      False              False   
3                         False                      False              False   
4                         False                      False              False   
...                         ...                        ...                ...   
23957                      True                       True              False   
23958                      True                       True              False   
23959                      True                       True              False   
23960                      True                       True              False   
23961                      True                       True              False   

       ID-VN Charlotte (Small feeder)  BE-CA Belafonte (Post-Panamax)  \
0                               False                           False   
1                               False                           False   
2                               False                           False   
3                               False                           False   
4                               False                           False   
...                               ...                             ...   
23957                            True                            True   
23958                            True                            True   
23959                            True                            True   
23960                            True                            True   
23961                            True                            True   

       MT-TH Speranza (New Panamax)  GR-ES China (ULCV)  \
0                             False               False   
1                             False               False   
2                             False               False   
3                             False               False   
4                             False               False   
...                             ...                 ...   
23957                          True                True   
23958                          True                True   
23959                          True                True   
23960                          True                True   
23961                          True                True   

       VN-SA Corsair (New Panamax)  ES-TW Altair (Feedermax)  \
0                            False                     False   
1                            False                     False   
2                            False                     False   
3                            False                     False   
4                            False                     False   
...                            ...                       ...   
23957                         True                      True   
23958                         True                      True   
23959                         True                      True   
23960                         True                      True   
23961                         True                      True   

       SA-ES Tankadère (Feedermax)  ...  BE-SA Cithara (ULCV)  \
0                            False  ...                 False   
1                            False  ...                 False   
2                            False  ...                 False   
3                            False  ...                 False   
4                            False  ...                 False   
...                            ...  ...                   ...   
23957                         True  ...                  True   
23958                         True  ...                  True   
23959                         True  ...                  True   
23960                        

In [149]:
liczba_pustych = np.column_stack([ df_isna[col].sum() for col in df_isna ])
liczba_pustych

array([[21066, 11420,     0, 23045, 18855, 13105,  4448, 13822, 21664,
        21161,  7533, 21543, 18586, 22586, 20240, 10986, 23058, 20508,
        22458, 14303, 22871,  3250, 17550, 23016, 21735, 23114, 21198,
        22556, 21736, 11741,  2227,  1627, 19654, 23053, 21559, 19237,
         6798, 10160, 22005,  1840,  5706,  9195, 21061,  4609, 12936,
        12785, 23071, 16030, 19395]], dtype=int64)

In [139]:
col = df.columns
col

Index(['LK-SG Nellie (Feedermax)', 'PA-OM Ghost (New Panamax)',
       'GR-BE Blue (ULCV)', 'ID-VN Charlotte (Small feeder)',
       'BE-CA Belafonte (Post-Panamax)', 'MT-TH Speranza (New Panamax)',
       'GR-ES China (ULCV)', 'VN-SA Corsair (New Panamax)',
       'ES-TW Altair (Feedermax)', 'SA-ES Tankadère (Feedermax)',
       'KP-MY Gotha (ULCV)', 'ID-BR Cassidy (Feedermax)',
       'GR-TH Nautilus (Post-Panamax)', 'MT-MY Harekaze (Feeder)',
       'VN-VN Neptune (Panamax)', 'DE-MY Argonaut (New Panamax)',
       'KP-MY Odessa (Small feeder)', 'JP-IN Anchises (Panamax)',
       'MY-DE Seagallop (Feeder)', 'MA-ES Grayfish (Post-Panamax)',
       'CA-KP Reaper (Feeder)', 'KP-NL Tasha (ULCV)',
       'GR-BE Aeolus (Post-Panamax)', 'AE-IN Illustria (Small feeder)',
       'BE-GR Argonautica (Feedermax)', 'PA-ES Pocahontas (Small feeder)',
       'KP-GR Covenant (Feedermax)', 'MA-PA Ning-Po (Feeder)',
       'MT-MY Demeter (Feedermax)', 'DE-BE Siren (New Panamax)',
       'GB-IN Argo (U

In [142]:
df.shape

(23962, 49)

In [150]:
final_liczba_kontenerow = pd.DataFrame(data=23962 - liczba_pustych, columns=col)
final_liczba_kontenerow

LK-SG Nellie (Feedermax)  PA-OM Ghost (New Panamax)  GR-BE Blue (ULCV)  \
0                      2896                      12542              23962   

   ID-VN Charlotte (Small feeder)  BE-CA Belafonte (Post-Panamax)  \
0                             917                            5107   

   MT-TH Speranza (New Panamax)  GR-ES China (ULCV)  \
0                         10857               19514   

   VN-SA Corsair (New Panamax)  ES-TW Altair (Feedermax)  \
0                        10140                      2298   

   SA-ES Tankadère (Feedermax)  ...  BE-SA Cithara (ULCV)  \
0                         2801  ...                 22122   

   SG-TH Pushkin (ULCV)  MT-IN Astrea (ULCV)  BR-US Grossadler (Feedermax)  \
0                 18256                14767                          2901   

   SA-BR Arabella (ULCV)  ES-GR Henrietta (New Panamax)  \
0                  19353                          11026   

   MA-MT Dazzler (New Panamax)  PA-MT Chelsea (Small feeder)  \
0                        11177                           891   

   SG-US Literature (Post-Panamax)  AE-IN Unicorn (Panamax)  
0                             7932                     4567  

[1 rows x 49 columns]

In [156]:
final_liczba_kontenerow.columns

Index(['LK-SG Nellie (Feedermax)', 'PA-OM Ghost (New Panamax)',
       'GR-BE Blue (ULCV)', 'ID-VN Charlotte (Small feeder)',
       'BE-CA Belafonte (Post-Panamax)', 'MT-TH Speranza (New Panamax)',
       'GR-ES China (ULCV)', 'VN-SA Corsair (New Panamax)',
       'ES-TW Altair (Feedermax)', 'SA-ES Tankadère (Feedermax)',
       'KP-MY Gotha (ULCV)', 'ID-BR Cassidy (Feedermax)',
       'GR-TH Nautilus (Post-Panamax)', 'MT-MY Harekaze (Feeder)',
       'VN-VN Neptune (Panamax)', 'DE-MY Argonaut (New Panamax)',
       'KP-MY Odessa (Small feeder)', 'JP-IN Anchises (Panamax)',
       'MY-DE Seagallop (Feeder)', 'MA-ES Grayfish (Post-Panamax)',
       'CA-KP Reaper (Feeder)', 'KP-NL Tasha (ULCV)',
       'GR-BE Aeolus (Post-Panamax)', 'AE-IN Illustria (Small feeder)',
       'BE-GR Argonautica (Feedermax)', 'PA-ES Pocahontas (Small feeder)',
       'KP-GR Covenant (Feedermax)', 'MA-PA Ning-Po (Feeder)',
       'MT-MY Demeter (Feedermax)', 'DE-BE Siren (New Panamax)',
       'GB-IN Argo (U

In [169]:
col = final_liczba_kontenerow.columns.copy()
col

Index(['LK-SG Nellie (Feedermax)', 'PA-OM Ghost (New Panamax)',
       'GR-BE Blue (ULCV)', 'ID-VN Charlotte (Small feeder)',
       'BE-CA Belafonte (Post-Panamax)', 'MT-TH Speranza (New Panamax)',
       'GR-ES China (ULCV)', 'VN-SA Corsair (New Panamax)',
       'ES-TW Altair (Feedermax)', 'SA-ES Tankadère (Feedermax)',
       'KP-MY Gotha (ULCV)', 'ID-BR Cassidy (Feedermax)',
       'GR-TH Nautilus (Post-Panamax)', 'MT-MY Harekaze (Feeder)',
       'VN-VN Neptune (Panamax)', 'DE-MY Argonaut (New Panamax)',
       'KP-MY Odessa (Small feeder)', 'JP-IN Anchises (Panamax)',
       'MY-DE Seagallop (Feeder)', 'MA-ES Grayfish (Post-Panamax)',
       'CA-KP Reaper (Feeder)', 'KP-NL Tasha (ULCV)',
       'GR-BE Aeolus (Post-Panamax)', 'AE-IN Illustria (Small feeder)',
       'BE-GR Argonautica (Feedermax)', 'PA-ES Pocahontas (Small feeder)',
       'KP-GR Covenant (Feedermax)', 'MA-PA Ning-Po (Feeder)',
       'MT-MY Demeter (Feedermax)', 'DE-BE Siren (New Panamax)',
       'GB-IN Argo (U

In [177]:
col = col.tolist()

In [179]:
col[1]

'PA-OM Ghost (New Panamax)'

In [189]:
temp_col = [i.split('(', 2)[1] for i in col].copy()
temp_col

['Feedermax)',
 'New Panamax)',
 'ULCV)',
 'Small feeder)',
 'Post-Panamax)',
 'New Panamax)',
 'ULCV)',
 'New Panamax)',
 'Feedermax)',
 'Feedermax)',
 'ULCV)',
 'Feedermax)',
 'Post-Panamax)',
 'Feeder)',
 'Panamax)',
 'New Panamax)',
 'Small feeder)',
 'Panamax)',
 'Feeder)',
 'Post-Panamax)',
 'Feeder)',
 'ULCV)',
 'Post-Panamax)',
 'Small feeder)',
 'Feedermax)',
 'Small feeder)',
 'Feedermax)',
 'Feeder)',
 'Feedermax)',
 'New Panamax)',
 'ULCV)',
 'ULCV)',
 'Panamax)',
 'Small feeder)',
 'Feedermax)',
 'Panamax)',
 'ULCV)',
 'New Panamax)',
 'Feeder)',
 'ULCV)',
 'ULCV)',
 'ULCV)',
 'Feedermax)',
 'ULCV)',
 'New Panamax)',
 'New Panamax)',
 'Small feeder)',
 'Post-Panamax)',
 'Panamax)']

In [193]:
col_final = [i.split(')', 2)[0] for i in temp_col].copy()
col_final

['Feedermax',
 'New Panamax',
 'ULCV',
 'Small feeder',
 'Post-Panamax',
 'New Panamax',
 'ULCV',
 'New Panamax',
 'Feedermax',
 'Feedermax',
 'ULCV',
 'Feedermax',
 'Post-Panamax',
 'Feeder',
 'Panamax',
 'New Panamax',
 'Small feeder',
 'Panamax',
 'Feeder',
 'Post-Panamax',
 'Feeder',
 'ULCV',
 'Post-Panamax',
 'Small feeder',
 'Feedermax',
 'Small feeder',
 'Feedermax',
 'Feeder',
 'Feedermax',
 'New Panamax',
 'ULCV',
 'ULCV',
 'Panamax',
 'Small feeder',
 'Feedermax',
 'Panamax',
 'ULCV',
 'New Panamax',
 'Feeder',
 'ULCV',
 'ULCV',
 'ULCV',
 'Feedermax',
 'ULCV',
 'New Panamax',
 'New Panamax',
 'Small feeder',
 'Post-Panamax',
 'Panamax']

In [221]:
final_2_question = pd.DataFrame(data=23962 - liczba_pustych, columns=col_final)
final_2_question

Feedermax  New Panamax   ULCV  Small feeder  Post-Panamax  New Panamax  \
0       2896        12542  23962           917          5107        10857   

    ULCV  New Panamax  Feedermax  Feedermax  ...   ULCV   ULCV   ULCV  \
0  19514        10140       2298       2801  ...  22122  18256  14767   

   Feedermax   ULCV  New Panamax  New Panamax  Small feeder  Post-Panamax  \
0       2901  19353        11026        11177           891          7932   

   Panamax  
0     4567  

[1 rows x 49 columns]

In [222]:
final_2_question = final_2_question.T.copy()
final_2_question.head()

0
Feedermax      2896
New Panamax   12542
ULCV          23962
Small feeder    917
Post-Panamax   5107

In [226]:
final_2_question = final_2_question.reset_index()
final_2_question.head(10)

index      0
0     Feedermax   2896
1   New Panamax  12542
2          ULCV  23962
3  Small feeder    917
4  Post-Panamax   5107
5   New Panamax  10857
6          ULCV  19514
7   New Panamax  10140
8     Feedermax   2298
9     Feedermax   2801

In [228]:
srednio_max = final_2_question.groupby(['index']).mean()
srednio_max

0
index                     
Feeder         1466.800000
Feedermax      2548.333333
New Panamax   11842.625000
Panamax        4155.200000
Post-Panamax   6897.200000
Small feeder    902.500000
ULCV          19668.090909

# PYTANIE NR. 3 Jaka jest średnia waga kontenera z przetworami owocowymi (A3) z dokładnością do 1 kg np: 1234? (zaokrąglane w górę) – 20 pkt

In [229]:
fruits = np.column_stack([ df[s].str.contains("/A3@", na=False) for s in df ])
fruits

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [230]:
fruits.sum(where = True)

28864

In [231]:
# (23962, 49)
fruits.shape

(23962, 49)

In [234]:
find_result = np.where(fruits==True)
find_result

(array([    0,     0,     0, ..., 23889, 23896, 23943], dtype=int64),
 array([ 7, 15, 19, ...,  2,  2,  2], dtype=int64))

In [235]:
type(find_result)

tuple

In [237]:
find_result[0]

array([    0,     0,     0, ..., 23889, 23896, 23943], dtype=int64)

In [243]:
df.iloc[1,1]

'PA-OM-51292344/2432/Y2@cnnlgrt.ml/11242'

In [244]:
iter = len(find_result[0])
iter

28864

In [255]:
list_new=[]
for i in range (0,iter):
    temp = df.iloc[find_result[0][i],find_result[1][i]]
    list_new.append(temp)
list_new    

['TH-SA-52347518/3566/A3@gzisqdnt.my/8813',
 'DE-MY-14594401/2943/A3@orsuoix.mf/62658',
 'MA-ES-99644461/3077/A3@rdajxe.ar/47910',
 'BR-US-07900956/4151/A3@hibktyjq.ar/35773',
 'PA-ES-57172208/2476/A3@cnvjcjtpi.sy/86700',
 'GB-OM-65081318/1804/A3@ejzxgzqc.mt/30702',
 'US-IN-31852284/2689/A3@rkzan.ba/93779',
 'BR-US-28952353/2751/A3@dophbxhl.af/25077',
 'SA-ES-13902353/2942/A3@hsxpkywomc.na/86488',
 'MA-MT-41937849/1424/A3@aewcb.hr/4911',
 'OM-PA-51672029/4258/A3@ayzqyd.sm/59569',
 'MT-MY-56311601/1790/A3@wrvjys.sm/61274',
 'DE-BE-61056140/3269/A3@jbw.bi/37566',
 'MA-MT-16607118/3869/A3@gixtx.pa/23861',
 'VN-SA-11216612/1987/A3@apsblucn.se/13440',
 'MY-KP-42781189/4233/A3@okandle.sh/94036',
 'DE-TH-28299502/1138/A3@adgcqxb.td/63633',
 'SA-MY-98308219/3671/A3@awcbhrswe.na/47831',
 'MY-SG-46806101/2445/A3@eff.gg/91940',
 'SA-VN-00248963/2075/A3@xlvjaxwx.ps/31252',
 'BR-NL-98609558/1849/A3@ctmv.tk/13838',
 'PH-SA-12679998/2824/A3@kqjxfj.mn/39602',
 'DE-MY-52023597/2758/A3@ltg.hr/1480',
 'K

In [256]:
len(list_new)

28864

In [257]:
list_new = [i.split('/', 2)[1] for i in list_new].copy()
list_new

['3566',
 '2943',
 '3077',
 '4151',
 '2476',
 '1804',
 '2689',
 '2751',
 '2942',
 '1424',
 '4258',
 '1790',
 '3269',
 '3869',
 '1987',
 '4233',
 '1138',
 '3671',
 '2445',
 '2075',
 '1849',
 '2824',
 '2758',
 '3757',
 '3626',
 '4506',
 '2702',
 '2688',
 '3911',
 '1959',
 '3435',
 '2256',
 '3398',
 '3407',
 '2223',
 '1780',
 '3913',
 '3757',
 '2892',
 '4293',
 '4674',
 '2296',
 '1706',
 '3037',
 '2162',
 '4537',
 '4493',
 '3034',
 '2381',
 '3785',
 '2026',
 '3697',
 '1811',
 '1375',
 '1413',
 '3532',
 '1801',
 '4219',
 '4184',
 '4237',
 '1284',
 '4426',
 '1602',
 '2717',
 '4087',
 '4502',
 '4424',
 '4134',
 '4020',
 '1686',
 '3286',
 '4005',
 '2703',
 '2155',
 '3437',
 '4056',
 '2658',
 '2311',
 '1498',
 '2732',
 '4270',
 '2363',
 '2973',
 '3822',
 '1735',
 '2980',
 '2769',
 '2576',
 '3235',
 '3010',
 '3527',
 '4715',
 '2791',
 '2732',
 '2174',
 '4555',
 '3975',
 '4135',
 '4482',
 '1247',
 '4240',
 '3688',
 '3792',
 '2625',
 '3064',
 '2967',
 '1980',
 '4396',
 '1504',
 '4206',
 '1247',
 

In [268]:
int(list_new[0])

3566

In [271]:
len(list_new)

28864

In [272]:
u=[]
for i in range (0, 28864):
    u.append(int(list_new[i]))
u    

[3566,
 2943,
 3077,
 4151,
 2476,
 1804,
 2689,
 2751,
 2942,
 1424,
 4258,
 1790,
 3269,
 3869,
 1987,
 4233,
 1138,
 3671,
 2445,
 2075,
 1849,
 2824,
 2758,
 3757,
 3626,
 4506,
 2702,
 2688,
 3911,
 1959,
 3435,
 2256,
 3398,
 3407,
 2223,
 1780,
 3913,
 3757,
 2892,
 4293,
 4674,
 2296,
 1706,
 3037,
 2162,
 4537,
 4493,
 3034,
 2381,
 3785,
 2026,
 3697,
 1811,
 1375,
 1413,
 3532,
 1801,
 4219,
 4184,
 4237,
 1284,
 4426,
 1602,
 2717,
 4087,
 4502,
 4424,
 4134,
 4020,
 1686,
 3286,
 4005,
 2703,
 2155,
 3437,
 4056,
 2658,
 2311,
 1498,
 2732,
 4270,
 2363,
 2973,
 3822,
 1735,
 2980,
 2769,
 2576,
 3235,
 3010,
 3527,
 4715,
 2791,
 2732,
 2174,
 4555,
 3975,
 4135,
 4482,
 1247,
 4240,
 3688,
 3792,
 2625,
 3064,
 2967,
 1980,
 4396,
 1504,
 4206,
 1247,
 4649,
 4401,
 4008,
 3831,
 4478,
 4084,
 3515,
 2736,
 3338,
 1398,
 2674,
 1613,
 1984,
 2257,
 3176,
 3003,
 1721,
 3620,
 3139,
 3920,
 1813,
 1163,
 2075,
 3749,
 4520,
 4119,
 2013,
 1770,
 1918,
 2760,
 3386,
 3700,

In [273]:
len(u)

28864

In [280]:
arr = np.array(u)
arr.mean()

2923.433411862528

# PYTANIE NR. 4 Która Polska firma globalnie przewozi najwięcej kontenerów? (nazwa firmy) – 25 pkt

In [3]:
df_4 = df.copy()
df_4.head()

LK-SG Nellie (Feedermax)  \
0    MA-SG-83996625/2585/A1@oxlyo.uk/6145   
1  LK-SG-65041225/2292/X2@kldkrh.hr/99361   
2   LK-SG-56103708/2888/Z1@husvb.cl/93519   
3    LK-SG-34905922/2908/A2@jeck.ar/67001   
4   LK-SG-70365073/2973/B3@uexkc.ne/32974   

                 PA-OM Ghost (New Panamax)  \
0      PA-ES-96031647/2993/B2@tuw.ml/94044   
1  PA-OM-51292344/2432/Y2@cnnlgrt.ml/11242   
2      SA-SA-73465451/1924/B3@rej.ba/38170   
3    PA-ID-94657093/2370/X2@jpllu.ls/93944   
4     PA-OM-34467231/4591/Y2@hoox.ca/18710   

                           GR-BE Blue (ULCV)  \
0  MY-BE-40283751/4079/X1@nxocoezoq.mp/96326   
1     GR-BE-20853894/2657/Y2@rlzkic.dk/19799   
2       SA-GB-27472314/1430/Y2@vwit.ne/62695   
3       GR-BE-26706350/3679/X1@tjpy.ua/92050   
4   GR-BE-66955426/2830/Y2@ssaysqgy.nz/81484   

            ID-VN Charlotte (Small feeder)  \
0   ID-VN-33266337/3165/Y2@uineka.se/69047   
1    BE-BE-29634771/2841/Z1@aerrv.pa/98217   
2  ID-VN-85411865/2549/B2@upthpgw.sb/87360   
3    ID-VN-15537738/3270/Y2@dtpcc.my/64445   
4     VN-IN-06555743/2249/Y1@ltor.ne/40761   

               BE-CA Belafonte (Post-Panamax)  \
0        BE-CA-89905813/3223/C2@ltor.ne/68920   
1        BE-CA-38311826/3576/B3@jbkk.bf/71926   
2      BE-CA-42006271/1499/C1@pvvvtv.my/92789   
3  BE-CA-02105662/4492/Y1@irmqicyeym.cl/91984   
4     TH-CA-75372193/1736/Z1@pzhdqej.mn/13050   

              MT-TH Speranza (New Panamax)  \
0  MT-TH-24923449/3639/C1@gpkapat.ge/53411   
1  DE-TH-62431607/1371/A1@qclajsg.ba/65645   
2    PH-TH-23141480/4337/C2@fukcw.sh/76034   
3    IN-LK-92283518/2950/A2@bqsbs.nz/38914   
4      MT-TH-15078686/3388/A1@mju.co/56044   

                           GR-ES China (ULCV)  \
0  ES-ES-05199984/1845/B2@recfkuwwsb.ml/19278   
1        GR-ES-74799208/4373/A2@srbh.cl/51634   
2        VN-MT-71958819/4118/X2@ofjx.af/42364   
3       PA-ES-28310638/4323/C3@psrun.ca/96238   
4  SA-ES-13902353/2942/A3@hsxpkywomc.na/86488   

                 VN-SA Corsair (New Panamax)  \
0    TH-SA-52347518/3566/A3@gzisqdnt.my/8813   
1      PH-SA-51770171/2249/A2@vmrxb.at/62140   
2  VN-SA-22726083/2238/B3@macsamsyj.mf/46624   
3   VN-SA-69444675/1857/A2@egkobucw.ge/95057   
4    VN-SA-09898403/2190/Y2@euvzdhh.ls/13709   

                     ES-TW Altair (Feedermax)  \
0       ES-GR-37106935/3029/C2@stpsdv.fi/9291   
1   PA-TH-25471644/2492/C3@nxocoezoq.mp/47376   
2         PH-TW-03146399/2033/Z1@xlwx.ls/4574   
3  ES-IN-73522503/3425/B3@ztxvgwpitj.at/66720   
4       MT-TW-83861023/3034/Z1@gsvub.sm/78964   

                 SA-ES Tankadère (Feedermax)  ...  \
0     SA-ES-37956461/3478/B3@bwzwzu.sy/83214  ...   
1       LK-ES-89417715/1422/A2@tlrg.gs/51074  ...   
2        SA-ES-97019635/3894/X1@kij.ml/57386  ...   
3      SA-ES-07195573/2586/A2@hhzfo.ca/97473  ...   
4  SA-ES-94014368/3324/B1@tpjdlrbcp.gq/45012  ...   

                         BE-SA Cithara (ULCV)  \
0      BE-SA-09382878/1696/X1@umaxcu.fi/72069   
1         JP-SA-87795748/3862/C2@pqn.cu/84394   
2  KP-SA-24955317/3070/Z1@wvjgexthvc.my/50507   
3      BE-SA-33286290/4291/X2@gfwqsv.pa/24733   
4      BE-SA-44722253/2862/B3@kzlmita.gm/4285   

                         SG-TH Pushkin (ULCV)  \
0  SG-TH-23167136/4103/C3@zavwszregx.mt/85995   
1        SG-TH-12922418/2289/C3@olzq.hr/44302   
2   SG-TH-72904123/3353/X2@fiogfdbcc.yt/26498   
3  SG-SG-34783081/1762/B1@fkqeselfiw.ps/85738   
4   SG-TH-83697637/4512/A2@urjryzsoj.dk/80954   

                          MT-IN Astrea (ULCV)  \
0     MT-IN-72455571/4036/B2@upthpgw.sb/29389   
1     MT-IN-39542774/3379/B1@rbojxpp.at/18632   
2  MT-IN-04125937/4466/X2@izjuykbkxa.pl/95825   
3       US-IN-31852284/2689/A3@rkzan.ba/93779   
4        MT-IN-21488006/3060/A2@aosl.nz/78592   

               BR-US Grossadler (Feedermax)  \
0    BR-US-41967990/2977/C3@nrmipw.sm/38715   
1  BR-US-07900956/4151/A3@hibktyjq.ar/35773   
2      BR-US-37097564/3180/A2@gwgs.ar/92155   
3  BR-US-28952353/2751/A3@dophbxhl.af/25077   
4       DE-ID

In [14]:
pol_comp = np.column_stack([ df_4[s].str.contains(".pl/", na=False) for s in df_4 ])
pol_comp

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [15]:
find_result = np.where(pol_comp==True)
find_result

(array([    1,     2,     2, ..., 23863, 23878, 23906], dtype=int64),
 array([29, 29, 33, ...,  2,  2,  2], dtype=int64))

In [16]:
iter = len(find_result[0])
iter

10262

In [17]:
lit_new=[]
for i in range (0,iter):
    temp = df.iloc[find_result[0][i],find_result[1][i]]
    lit_new.append(temp)
lit_new  

['CA-BE-46338588/2024/A1@ejszndy.pl/44736',
 'DE-BE-68806940/2280/C1@fkpha.pl/42161',
 'TW-NL-34614677/4377/Y2@kwhtwuyrn.pl/51569',
 'MT-IN-04125937/4466/X2@izjuykbkxa.pl/95825',
 'MA-PA-69682404/3810/C2@lvovxw.pl/11636',
 'PA-MY-22775528/1840/B1@phjhdanq.pl/70083',
 'MT-MT-34821125/3222/Y2@qdiku.pl/78916',
 'US-BE-92940632/4402/A2@tfdvcpejr.pl/56667',
 'MA-SA-12518127/3188/Y2@qocyydrs.pl/25483',
 'MA-PA-91636151/4506/A3@fkpha.pl/57953',
 'GR-TH-48339947/1423/C1@tggrpiizuq.pl/58232',
 'GR-DE-76800727/2932/Y2@eddaq.pl/42885',
 'PA-ES-15486179/3172/X2@tfdvcpejr.pl/63638',
 'KP-NL-50491735/4674/A3@qocyydrs.pl/69771',
 'GR-PA-51094034/3657/X1@hry.pl/66833',
 'BE-CA-28891915/1966/Y1@qezjqofcr.pl/68598',
 'ES-MY-65047246/2201/X1@gsnbdrua.pl/30352',
 'KP-GR-42916737/1413/A3@tyreqxsbw.pl/10295',
 'CA-KP-75504013/3238/B2@uezee.pl/65342',
 'MT-GR-92542989/1767/C3@mtlgobr.pl/84798',
 'TW-GR-22262098/3932/B1@ivg.pl/85555',
 'PA-MT-81314821/1484/B2@hry.pl/31662',
 'CA-GR-83734632/2551/B2@eddaq.pl/6

In [18]:
lit_new = [i.split('@', 2)[1] for i in lit_new].copy()
lit_new

['ejszndy.pl/44736',
 'fkpha.pl/42161',
 'kwhtwuyrn.pl/51569',
 'izjuykbkxa.pl/95825',
 'lvovxw.pl/11636',
 'phjhdanq.pl/70083',
 'qdiku.pl/78916',
 'tfdvcpejr.pl/56667',
 'qocyydrs.pl/25483',
 'fkpha.pl/57953',
 'tggrpiizuq.pl/58232',
 'eddaq.pl/42885',
 'tfdvcpejr.pl/63638',
 'qocyydrs.pl/69771',
 'hry.pl/66833',
 'qezjqofcr.pl/68598',
 'gsnbdrua.pl/30352',
 'tyreqxsbw.pl/10295',
 'uezee.pl/65342',
 'mtlgobr.pl/84798',
 'ivg.pl/85555',
 'hry.pl/31662',
 'eddaq.pl/67279',
 'dcagsokd.pl/38634',
 'vkdqzegd.pl/1155',
 'zqqyd.pl/69758',
 'qocyydrs.pl/22020',
 'ejszndy.pl/38013',
 'bruzck.pl/96072',
 'qezjqofcr.pl/58366',
 'gffjd.pl/11416',
 'izjuykbkxa.pl/29650',
 'eddaq.pl/65739',
 'tggrpiizuq.pl/70493',
 'xhrpz.pl/76191',
 'qdiku.pl/15363',
 'vtsfgtedl.pl/22995',
 'pvklvah.pl/41833',
 'dcagsokd.pl/64841',
 'phjhdanq.pl/13041',
 'tyreqxsbw.pl/89488',
 'znqjzwib.pl/44601',
 'tggrpiizuq.pl/27510',
 'nlqfl.pl/76647',
 'dcagsokd.pl/91412',
 'ejszndy.pl/31976',
 'qezjqofcr.pl/72650',
 'mtlgob

In [19]:
lit_new = [i.split('/', 2)[0] for i in lit_new].copy()
lit_new

['ejszndy.pl',
 'fkpha.pl',
 'kwhtwuyrn.pl',
 'izjuykbkxa.pl',
 'lvovxw.pl',
 'phjhdanq.pl',
 'qdiku.pl',
 'tfdvcpejr.pl',
 'qocyydrs.pl',
 'fkpha.pl',
 'tggrpiizuq.pl',
 'eddaq.pl',
 'tfdvcpejr.pl',
 'qocyydrs.pl',
 'hry.pl',
 'qezjqofcr.pl',
 'gsnbdrua.pl',
 'tyreqxsbw.pl',
 'uezee.pl',
 'mtlgobr.pl',
 'ivg.pl',
 'hry.pl',
 'eddaq.pl',
 'dcagsokd.pl',
 'vkdqzegd.pl',
 'zqqyd.pl',
 'qocyydrs.pl',
 'ejszndy.pl',
 'bruzck.pl',
 'qezjqofcr.pl',
 'gffjd.pl',
 'izjuykbkxa.pl',
 'eddaq.pl',
 'tggrpiizuq.pl',
 'xhrpz.pl',
 'qdiku.pl',
 'vtsfgtedl.pl',
 'pvklvah.pl',
 'dcagsokd.pl',
 'phjhdanq.pl',
 'tyreqxsbw.pl',
 'znqjzwib.pl',
 'tggrpiizuq.pl',
 'nlqfl.pl',
 'dcagsokd.pl',
 'ejszndy.pl',
 'qezjqofcr.pl',
 'mtlgobr.pl',
 'nlqfl.pl',
 'fkpha.pl',
 'xhrpz.pl',
 'dcagsokd.pl',
 'wznire.pl',
 'dcagsokd.pl',
 'mrxjn.pl',
 'ehcgxr.pl',
 'wznire.pl',
 'xrjrouir.pl',
 'ovvkykrf.pl',
 'hry.pl',
 'ovvkykrf.pl',
 'fkpha.pl',
 'tggrpiizuq.pl',
 'vkdqzegd.pl',
 'phjhdanq.pl',
 'dcagsokd.pl',
 'bgbujhjd

In [20]:
lit_new = [i.split('.pl', 2)[0] for i in lit_new].copy()
lit_new

['ejszndy',
 'fkpha',
 'kwhtwuyrn',
 'izjuykbkxa',
 'lvovxw',
 'phjhdanq',
 'qdiku',
 'tfdvcpejr',
 'qocyydrs',
 'fkpha',
 'tggrpiizuq',
 'eddaq',
 'tfdvcpejr',
 'qocyydrs',
 'hry',
 'qezjqofcr',
 'gsnbdrua',
 'tyreqxsbw',
 'uezee',
 'mtlgobr',
 'ivg',
 'hry',
 'eddaq',
 'dcagsokd',
 'vkdqzegd',
 'zqqyd',
 'qocyydrs',
 'ejszndy',
 'bruzck',
 'qezjqofcr',
 'gffjd',
 'izjuykbkxa',
 'eddaq',
 'tggrpiizuq',
 'xhrpz',
 'qdiku',
 'vtsfgtedl',
 'pvklvah',
 'dcagsokd',
 'phjhdanq',
 'tyreqxsbw',
 'znqjzwib',
 'tggrpiizuq',
 'nlqfl',
 'dcagsokd',
 'ejszndy',
 'qezjqofcr',
 'mtlgobr',
 'nlqfl',
 'fkpha',
 'xhrpz',
 'dcagsokd',
 'wznire',
 'dcagsokd',
 'mrxjn',
 'ehcgxr',
 'wznire',
 'xrjrouir',
 'ovvkykrf',
 'hry',
 'ovvkykrf',
 'fkpha',
 'tggrpiizuq',
 'vkdqzegd',
 'phjhdanq',
 'dcagsokd',
 'bgbujhjdgz',
 'pfiujcu',
 'eddaq',
 'ejszndy',
 'tyreqxsbw',
 'ehcgxr',
 'bruzck',
 'ejszndy',
 'znqjzwib',
 'ivg',
 'znqjzwib',
 'jnhzen',
 'vkdqzegd',
 'tyreqxsbw',
 'qocyydrs',
 'ovvkykrf',
 'ksq',
 'edd

In [21]:
ones = np.ones(iter)
ones

array([1., 1., 1., ..., 1., 1., 1.])

In [23]:
#create dataframe for group by
d = {'col' : lit_new, 'col2' : ones}
df_temp = pd.DataFrame(data = d)
df_temp

col  col2
0         ejszndy   1.0
1           fkpha   1.0
2       kwhtwuyrn   1.0
3      izjuykbkxa   1.0
4          lvovxw   1.0
...           ...   ...
10257     pvklvah   1.0
10258       uezee   1.0
10259       gffjd   1.0
10260  hhnkdkrfsr   1.0
10261       qdiku   1.0

[10262 rows x 2 columns]

In [31]:
df_temp.groupby(['col']).count().sort_values(['col2'], ascending=False)

col2
col             
qdiku        274
ehcgxr       273
xhrpz        270
dcagsokd     268
pvklvah      265
hry          264
lvovxw       262
ovvkykrf     259
ksq          256
wznire       256
gsnbdrua     255
kwhtwuyrn    254
mtlgobr      253
xrjrouir     253
qezjqofcr    253
eddaq        250
qocyydrs     249
phjhdanq     247
pfiujcu      243
bgbujhjdgz   243
mrxjn        242
ejszndy      241
ivg          241
chseeqlzl    240
znqjzwib     239
huohoarfej   238
vkdqzegd     237
tfdvcpejr    237
nlqfl        237
hhnkdkrfsr   236
jnhzen       236
bruzck       234
tyreqxsbw    234
gfedq        232
vtsfgtedl    231
uezee        230
gffjd        229
izjuykbkxa   228
tggrpiizuq   224
fkpha        224
zqqyd        219
rxlkbd       206

# PYTANIE NR. 5 Jakiego typu ładunek o największej wartości eksportują Niemieckie firmy z Niemiec? (wartość to stosunek ceny do wagi) – 25 pkt

In [63]:
de = np.column_stack([ df_4[s].str.startswith('DE-', na=False) for s in df_4 ])
res_de = np.where(de==True)
iter = len(res_de[1])
iter

21147

In [64]:
list_de=[]
for i in range (0,iter):
    temp = df.iloc[res_de[0][i],res_de[1][i]]
    list_de.append(temp)
    
list_de = pd.DataFrame(data = list_de)
list_de

0
0       DE-MY-14594401/2943/A3@orsuoix.mf/62658
1       DE-TH-62431607/1371/A1@qclajsg.ba/65645
2      DE-MY-87645512/2259/X1@rvufpkws.yt/56447
3         DE-BE-68806940/2280/C1@fkpha.pl/42161
4      DE-MY-56079867/1474/Y1@vggxjhxx.my/75353
...                                         ...
21142     DE-BE-92031666/1826/B2@bkvub.hr/23661
21143   DE-BE-79482447/1390/X1@vrnnwgy.td/48470
21144     DE-BE-41452942/3484/A3@gzqrz.at/70412
21145  DE-BE-51968790/3096/A2@lkfrvdiq.at/59646
21146       DE-BR-60964988/1835/C2@lnx.sb/56956

[21147 rows x 1 columns]

In [65]:
de_de = np.column_stack([ list_de[s].str.contains('.de/', na=False) for s in list_de ])
res_dde = np.where(de_de==True)
iter = len(res_dde[1])
iter

231

In [72]:
list_final=[]
for i in range (0,iter):
    teemp = list_de.iloc[res_dde[0][i],res_dde[1][i]]
    list_final.append(teemp)
    
list_final    

['DE-BE-78220071/4270/Y1@lwgp.de/64032',
 'DE-MT-67598033/3738/X2@avjbzrijjj.de/40366',
 'DE-IN-98026037/3168/X2@rluzelu.de/98761',
 'DE-US-87025736/2831/Z1@fpa.de/59993',
 'DE-MY-36985361/3592/C1@bevwbyy.de/62380',
 'DE-MY-31679804/2066/B2@oet.de/54764',
 'DE-LK-59271157/3549/B1@iysaptycw.de/10041',
 'DE-BE-15782738/2080/X2@sufbzv.de/36157',
 'DE-JP-46012368/1456/B1@gohv.de/33561',
 'DE-MY-25027503/2760/C2@vih.de/9162',
 'DE-KP-86991467/3508/Y2@dqxzenyxbw.de/17836',
 'DE-GR-60088224/3359/A3@cixj.de/34864',
 'DE-ES-72440621/3079/B2@sufbzv.de/14362',
 'DE-MY-60166939/2843/Z1@lwgp.de/25554',
 'DE-MY-76965215/3841/X1@jardshh.de/26666',
 'DE-TH-74820780/3518/C1@sufbzv.de/83118',
 'DE-BE-15652126/1979/B2@fpa.de/38348',
 'DE-MY-91546005/4683/X1@rluzelu.de/61380',
 'DE-BE-87391413/4340/B1@rluzelu.de/2323',
 'DE-MY-91026462/2796/Y1@kzvjxky.de/93313',
 'DE-MY-17679480/1633/Z1@avjbzrijjj.de/69341',
 'DE-BE-21081913/3176/C2@lwgp.de/36669',
 'DE-SG-01380514/4064/C2@yjiuh.de/92417',
 'DE-BE-2862000

In [73]:
array_length = len(list_final)
array_length

231

In [70]:
list_final = pd.DataFrame(list_final)

In [83]:
list_final[0:4]

['DE-BE-78220071/4270/Y1@lwgp.de/64032',
 'DE-MT-67598033/3738/X2@avjbzrijjj.de/40366',
 'DE-IN-98026037/3168/X2@rluzelu.de/98761',
 'DE-US-87025736/2831/Z1@fpa.de/59993']

In [90]:
searchfor = ['/', '@']
lit_new = [i.split(r'[/@]', 3) for i in list_final].copy()
lit_new

[['DE-BE-78220071/4270/Y1@lwgp.de/64032'],
 ['DE-MT-67598033/3738/X2@avjbzrijjj.de/40366'],
 ['DE-IN-98026037/3168/X2@rluzelu.de/98761'],
 ['DE-US-87025736/2831/Z1@fpa.de/59993'],
 ['DE-MY-36985361/3592/C1@bevwbyy.de/62380'],
 ['DE-MY-31679804/2066/B2@oet.de/54764'],
 ['DE-LK-59271157/3549/B1@iysaptycw.de/10041'],
 ['DE-BE-15782738/2080/X2@sufbzv.de/36157'],
 ['DE-JP-46012368/1456/B1@gohv.de/33561'],
 ['DE-MY-25027503/2760/C2@vih.de/9162'],
 ['DE-KP-86991467/3508/Y2@dqxzenyxbw.de/17836'],
 ['DE-GR-60088224/3359/A3@cixj.de/34864'],
 ['DE-ES-72440621/3079/B2@sufbzv.de/14362'],
 ['DE-MY-60166939/2843/Z1@lwgp.de/25554'],
 ['DE-MY-76965215/3841/X1@jardshh.de/26666'],
 ['DE-TH-74820780/3518/C1@sufbzv.de/83118'],
 ['DE-BE-15652126/1979/B2@fpa.de/38348'],
 ['DE-MY-91546005/4683/X1@rluzelu.de/61380'],
 ['DE-BE-87391413/4340/B1@rluzelu.de/2323'],
 ['DE-MY-91026462/2796/Y1@kzvjxky.de/93313'],
 ['DE-MY-17679480/1633/Z1@avjbzrijjj.de/69341'],
 ['DE-BE-21081913/3176/C2@lwgp.de/36669'],
 ['DE-SG-0138

In [98]:
len(lit_new)

231

# (wartość to stosunek ceny do wagi) 
# last numbers//yyyy

In [104]:
import re
z = re.split(r'[/@]', list_final[0])
z

['DE-BE-78220071', '4270', 'Y1', 'lwgp.de', '64032']

In [106]:
end = len(list_final)
end

231

In [113]:
end = len(list_final)
temp_list=[]
colnames = ['origin','weight','type','company','price']
for i in range (0, end):
    tym = re.split(r'[/@]', list_final[i])
    temp_list.append(tym)
temp_list = pd.DataFrame(data = temp_list, columns = colnames)
temp_list

origin weight type        company  price
0    DE-BE-78220071   4270   Y1        lwgp.de  64032
1    DE-MT-67598033   3738   X2  avjbzrijjj.de  40366
2    DE-IN-98026037   3168   X2     rluzelu.de  98761
3    DE-US-87025736   2831   Z1         fpa.de  59993
4    DE-MY-36985361   3592   C1     bevwbyy.de  62380
..              ...    ...  ...            ...    ...
226  DE-NL-63562166   3613   C1         fpa.de  88575
227  DE-SA-74535398   2346   C3   iysaptycw.de  71970
228  DE-NL-47248060   4378   X1  avjbzrijjj.de  66411
229  DE-IN-83835001   2116   Y1    lbvaoqca.de  83895
230  DE-TH-37762080   4304   A1    jcjrsplp.de  82305

[231 rows x 5 columns]

In [145]:
temp_list['price']= temp_list['price'].astype(int)

In [146]:
temp_list['weight']= temp_list['weight'].astype(int)

In [148]:
temp_list["value"] = temp_list["price"]/temp_list["weight"]

In [152]:
temp_list = temp_list[["type","value","price","weight"]]
temp_list.head()

type      value  price  weight
0   Y1  14.995785  64032    4270
1   X2  10.798823  40366    3738
2   X2  31.174558  98761    3168
3   Z1  21.191452  59993    2831
4   C1  17.366370  62380    3592

In [156]:
temp_list.sort_values(['value'],ascending=False)

type      value  price  weight
149   C1  83.748714  97651    1166
24    A1  74.229741  88853    1197
150   C1  61.296449  74230    1211
95    X2  61.281947  90636    1479
156   X2  57.967953  79590    1373
..   ...        ...    ...     ...
142   X1   1.344868   4547    3381
101   B3   0.761562   3491    4584
100   Y1   0.551892   2377    4307
18    B1   0.535253   2323    4340
151   C1   0.336805   1423    4225

[231 rows x 4 columns]